export let data = [
 {
  id: 11,
  title: "perfume Oil",
  description: "Mega Discount, Impression of A...",
  price: 13,
  discountPercentage: 8.4,
  rating: 4.26,
  stock: 65,
  brand: "Impression of Acqua Di Gio",
  category: "fragrances",
  thumbnail: "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
  images: "https://dummyjson.com/image/i/products/11/2.jpg",
 },
 {
  id: 13,
  title: " Oil",
  description: "Impression of A...",
  price: 15,
  discountPercentage: 5,
  rating: 4,
  stock: 65,
  brand: " Di Gio",
  category: "fragrances",
  thumbnail: "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
  images: "https://dummyjson.com/image/i/products/11/1.jpg",
 },
 {
  id: 14,
  title: " cat",
  description: "Impression of A...",
  price: 15,
  discountPercentage: 5,
  rating: 4,
  stock: 65,
  brand: " Di Gio",
  category: "fragrances",
  thumbnail: "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
  images: "https://dummyjson.com/image/i/products/11/1.jpg",
 },
 {
  id: 14,
  title: " dog",
  description: "Impression of A...",
  price: 15,
  discountPercentage: 5,
  rating: 4,
  stock: 65,
  brand: " Di Gio",
  category: "fragrances",
  thumbnail: "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
  images: "https://dummyjson.com/image/i/products/11/1.jpg",
 },
 {
  id: 15,
  title: " number",
  description: "Impression of A...",
  price: 15,
  discountPercentage: 5,
  rating: 4,
  stock: 65,
  brand: " Di Gio",
  category: "fragrances",
  thumbnail: "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
  images: "https://dummyjson.com/image/i/products/11/1.jpg",
 },
 {
  id: 16,
  title: " computer",
  description: "Impression of A...",
  price: 15,
  discountPercentage: 5,
  rating: 4,
  stock: 65,
  brand: " Di Gio",
  category: "fragrances",
  thumbnail: "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
  images: "https://dummyjson.com/image/i/products/11/1.jpg",
 },
 {
  id: 17,
  title: " Oil",
  description: "Impression of A...",
  price: 15,
  discountPercentage: 5,
  rating: 4,
  stock: 65,
  brand: " Di Gio",
  category: "fragrances",
  thumbnail: "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
  images: "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
 },
 {
  id: 18,
  title: " fragrances",
  description: "Impression of A...",
  price: 15,
  discountPercentage: 5,
  rating: 4,
  stock: 65,
  brand: " Di Gio",
  category: "fragrances",
  thumbnail: "https://dummyjson.com/image/i/products/11/thumbnail.jpg",
  images: "https://dummyjson.com/image/i/products/11/3.jpg",
 },
];
